//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.ClickHouseDataService.Tests
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// UpdateObjectTestBS.
    /// </summary>
    // *** Start programmer edit section *** (UpdateObjectTestBS CustomAttributes)

    // *** End programmer edit section *** (UpdateObjectTestBS CustomAttributes)
    [ICSSoft.STORMNET.AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class UpdateObjectTestBS : ICSSoft.STORMNET.Business.BusinessServer
    {
        
        // *** Start programmer edit section *** (UpdateObjectTestBS CustomMembers)

        // *** End programmer edit section *** (UpdateObjectTestBS CustomMembers)

        
        // *** Start programmer edit section *** (OnUpdateAggregatorUpdateObjectTest CustomAttributes)

        // *** End programmer edit section *** (OnUpdateAggregatorUpdateObjectTest CustomAttributes)
        public virtual ICSSoft.STORMNET.DataObject[] OnUpdateAggregatorUpdateObjectTest(NewPlatform.ClickHouseDataService.Tests.AggregatorUpdateObjectTest UpdatedObject)
        {
            // *** Start programmer edit section *** (OnUpdateAggregatorUpdateObjectTest)
            return new ICSSoft.STORMNET.DataObject[0];
            // *** End programmer edit section *** (OnUpdateAggregatorUpdateObjectTest)
        }
        
        // *** Start programmer edit section *** (OnUpdateMasterUpdateObjectTest CustomAttributes)

        // *** End programmer edit section *** (OnUpdateMasterUpdateObjectTest CustomAttributes)
        public virtual ICSSoft.STORMNET.DataObject[] OnUpdateMasterUpdateObjectTest(NewPlatform.ClickHouseDataService.Tests.MasterUpdateObjectTest UpdatedObject)
        {
            // *** Start programmer edit section *** (OnUpdateMasterUpdateObjectTest)
            return new ICSSoft.STORMNET.DataObject[0];
            // *** End programmer edit section *** (OnUpdateMasterUpdateObjectTest)
        }
        
        // *** Start programmer edit section *** (OnUpdateDetailUpdateObjectTest CustomAttributes)

        // *** End programmer edit section *** (OnUpdateDetailUpdateObjectTest CustomAttributes)
        public virtual ICSSoft.STORMNET.DataObject[] OnUpdateDetailUpdateObjectTest(NewPlatform.ClickHouseDataService.Tests.DetailUpdateObjectTest UpdatedObject)
        {
            // *** Start programmer edit section *** (OnUpdateDetailUpdateObjectTest)
            return new ICSSoft.STORMNET.DataObject[0];
            // *** End programmer edit section *** (OnUpdateDetailUpdateObjectTest)
        }
    }
}
