//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.ORM.ClickHouseDataService.Tests
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// UpdateObjectTestBS.
    /// </summary>
    // *** Start programmer edit section *** (UpdateObjectTestBS CustomAttributes)

    // *** End programmer edit section *** (UpdateObjectTestBS CustomAttributes)
    [ICSSoft.STORMNET.AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class UpdateObjectTestBS : ICSSoft.STORMNET.Business.BusinessServer
    {
        
        // *** Start programmer edit section *** (UpdateObjectTestBS CustomMembers)

        // *** End programmer edit section *** (UpdateObjectTestBS CustomMembers)

        
        // *** Start programmer edit section *** (UpdateObjectTestBS.OnUpdateAggregatorUpdateObjectTest NewPlatform.Flexberry.ORM.ClickHouseDataService.Tests.AggregatorUpdateObjectTest CustomAttributes)

        // *** End programmer edit section *** (UpdateObjectTestBS.OnUpdateAggregatorUpdateObjectTest NewPlatform.Flexberry.ORM.ClickHouseDataService.Tests.AggregatorUpdateObjectTest CustomAttributes)
        [ICSSoft.STORMNET.AccessType(ICSSoft.STORMNET.AccessType.none)]
        public virtual ICSSoft.STORMNET.DataObject[] OnUpdateAggregatorUpdateObjectTest(NewPlatform.Flexberry.ORM.ClickHouseDataService.Tests.AggregatorUpdateObjectTest UpdatedObject)
        {
            // *** Start programmer edit section *** (UpdateObjectTestBS.OnUpdateAggregatorUpdateObjectTest NewPlatform.Flexberry.ORM.ClickHouseDataService.Tests.AggregatorUpdateObjectTest method implementation)

            return null;
            // *** End programmer edit section *** (UpdateObjectTestBS.OnUpdateAggregatorUpdateObjectTest NewPlatform.Flexberry.ORM.ClickHouseDataService.Tests.AggregatorUpdateObjectTest method implementation)
        }
        
        // *** Start programmer edit section *** (UpdateObjectTestBS.OnUpdateDetailUpdateObjectTest NewPlatform.Flexberry.ORM.ClickHouseDataService.Tests.DetailUpdateObjectTest CustomAttributes)

        // *** End programmer edit section *** (UpdateObjectTestBS.OnUpdateDetailUpdateObjectTest NewPlatform.Flexberry.ORM.ClickHouseDataService.Tests.DetailUpdateObjectTest CustomAttributes)
        [ICSSoft.STORMNET.AccessType(ICSSoft.STORMNET.AccessType.none)]
        public virtual ICSSoft.STORMNET.DataObject[] OnUpdateDetailUpdateObjectTest(NewPlatform.Flexberry.ORM.ClickHouseDataService.Tests.DetailUpdateObjectTest UpdatedObject)
        {
            // *** Start programmer edit section *** (UpdateObjectTestBS.OnUpdateDetailUpdateObjectTest NewPlatform.Flexberry.ORM.ClickHouseDataService.Tests.DetailUpdateObjectTest method implementation)

            return null;
            // *** End programmer edit section *** (UpdateObjectTestBS.OnUpdateDetailUpdateObjectTest NewPlatform.Flexberry.ORM.ClickHouseDataService.Tests.DetailUpdateObjectTest method implementation)
        }
        
        // *** Start programmer edit section *** (UpdateObjectTestBS.OnUpdateMasterUpdateObjectTest NewPlatform.Flexberry.ORM.ClickHouseDataService.Tests.MasterUpdateObjectTest CustomAttributes)

        // *** End programmer edit section *** (UpdateObjectTestBS.OnUpdateMasterUpdateObjectTest NewPlatform.Flexberry.ORM.ClickHouseDataService.Tests.MasterUpdateObjectTest CustomAttributes)
        [ICSSoft.STORMNET.AccessType(ICSSoft.STORMNET.AccessType.none)]
        public virtual ICSSoft.STORMNET.DataObject[] OnUpdateMasterUpdateObjectTest(NewPlatform.Flexberry.ORM.ClickHouseDataService.Tests.MasterUpdateObjectTest UpdatedObject)
        {
            // *** Start programmer edit section *** (UpdateObjectTestBS.OnUpdateMasterUpdateObjectTest NewPlatform.Flexberry.ORM.ClickHouseDataService.Tests.MasterUpdateObjectTest method implementation)

            return null;
            // *** End programmer edit section *** (UpdateObjectTestBS.OnUpdateMasterUpdateObjectTest NewPlatform.Flexberry.ORM.ClickHouseDataService.Tests.MasterUpdateObjectTest method implementation)
        }
        
        // *** Start programmer edit section *** (OnUpdateAggregatorUpdateObjectTest CustomAttributes)

        // *** End programmer edit section *** (OnUpdateAggregatorUpdateObjectTest CustomAttributes)
        public virtual ICSSoft.STORMNET.DataObject[] OnUpdateAggregatorUpdateObjectTest(NewPlatform.Flexberry.ORM.ClickHouseDataService.Tests.AggregatorUpdateObjectTest UpdatedObject)
        {
            // *** Start programmer edit section *** (OnUpdateAggregatorUpdateObjectTest)

            return new ICSSoft.STORMNET.DataObject[0];
            // *** End programmer edit section *** (OnUpdateAggregatorUpdateObjectTest)
        }
        
        // *** Start programmer edit section *** (OnUpdateMasterUpdateObjectTest CustomAttributes)

        // *** End programmer edit section *** (OnUpdateMasterUpdateObjectTest CustomAttributes)
        public virtual ICSSoft.STORMNET.DataObject[] OnUpdateMasterUpdateObjectTest(NewPlatform.Flexberry.ORM.ClickHouseDataService.Tests.MasterUpdateObjectTest UpdatedObject)
        {
            // *** Start programmer edit section *** (OnUpdateMasterUpdateObjectTest)

            return new ICSSoft.STORMNET.DataObject[0];
            // *** End programmer edit section *** (OnUpdateMasterUpdateObjectTest)
        }
        
        // *** Start programmer edit section *** (OnUpdateDetailUpdateObjectTest CustomAttributes)

        // *** End programmer edit section *** (OnUpdateDetailUpdateObjectTest CustomAttributes)
        public virtual ICSSoft.STORMNET.DataObject[] OnUpdateDetailUpdateObjectTest(NewPlatform.Flexberry.ORM.ClickHouseDataService.Tests.DetailUpdateObjectTest UpdatedObject)
        {
            // *** Start programmer edit section *** (OnUpdateDetailUpdateObjectTest)

            return new ICSSoft.STORMNET.DataObject[0];
            // *** End programmer edit section *** (OnUpdateDetailUpdateObjectTest)
        }
    }
}
