//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.ClickHouseDataService.Tests
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// CombinedTypesUsageProviderTestClass.
    /// </summary>
    // *** Start programmer edit section *** (CombinedTypesUsageProviderTestClass CustomAttributes)

    // *** End programmer edit section *** (CombinedTypesUsageProviderTestClass CustomAttributes)
    [ClassStorage("CombinedTypesUsageProviderTest")]
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class CombinedTypesUsageProviderTestClass : NewPlatform.ClickHouseDataService.Tests.TypeNameUsageProviderTestClass
    {
        
        private NewPlatform.ClickHouseDataService.Tests.DataObjectForTest fDataObjectForTest;
        
        private NewPlatform.ClickHouseDataService.Tests.TypeUsageProviderTestClass fTypeUsageProviderTestClass;
        
        // *** Start programmer edit section *** (CombinedTypesUsageProviderTestClass CustomMembers)

        // *** End programmer edit section *** (CombinedTypesUsageProviderTestClass CustomMembers)

        
        /// <summary>
        /// CombinedTypesUsageProviderTestClass.
        /// </summary>
        // *** Start programmer edit section *** (CombinedTypesUsageProviderTestClass.DataObjectForTest CustomAttributes)

        // *** End programmer edit section *** (CombinedTypesUsageProviderTestClass.DataObjectForTest CustomAttributes)
        public virtual NewPlatform.ClickHouseDataService.Tests.DataObjectForTest DataObjectForTest
        {
            get
            {
                // *** Start programmer edit section *** (CombinedTypesUsageProviderTestClass.DataObjectForTest Get start)

                // *** End programmer edit section *** (CombinedTypesUsageProviderTestClass.DataObjectForTest Get start)
                NewPlatform.ClickHouseDataService.Tests.DataObjectForTest result = this.fDataObjectForTest;
                // *** Start programmer edit section *** (CombinedTypesUsageProviderTestClass.DataObjectForTest Get end)

                // *** End programmer edit section *** (CombinedTypesUsageProviderTestClass.DataObjectForTest Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (CombinedTypesUsageProviderTestClass.DataObjectForTest Set start)

                // *** End programmer edit section *** (CombinedTypesUsageProviderTestClass.DataObjectForTest Set start)
                this.fDataObjectForTest = value;
                // *** Start programmer edit section *** (CombinedTypesUsageProviderTestClass.DataObjectForTest Set end)

                // *** End programmer edit section *** (CombinedTypesUsageProviderTestClass.DataObjectForTest Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку NewPlatform.ClickHouseDataService.Tests.TypeUsageProviderTestClass.
        /// </summary>
        // *** Start programmer edit section *** (CombinedTypesUsageProviderTestClass.TypeUsageProviderTestClass CustomAttributes)

        // *** End programmer edit section *** (CombinedTypesUsageProviderTestClass.TypeUsageProviderTestClass CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "TypeUsageProviderTestClass"})]
        public virtual NewPlatform.ClickHouseDataService.Tests.TypeUsageProviderTestClass TypeUsageProviderTestClass
        {
            get
            {
                // *** Start programmer edit section *** (CombinedTypesUsageProviderTestClass.TypeUsageProviderTestClass Get start)

                // *** End programmer edit section *** (CombinedTypesUsageProviderTestClass.TypeUsageProviderTestClass Get start)
                NewPlatform.ClickHouseDataService.Tests.TypeUsageProviderTestClass result = this.fTypeUsageProviderTestClass;
                // *** Start programmer edit section *** (CombinedTypesUsageProviderTestClass.TypeUsageProviderTestClass Get end)

                // *** End programmer edit section *** (CombinedTypesUsageProviderTestClass.TypeUsageProviderTestClass Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (CombinedTypesUsageProviderTestClass.TypeUsageProviderTestClass Set start)

                // *** End programmer edit section *** (CombinedTypesUsageProviderTestClass.TypeUsageProviderTestClass Set start)
                this.fTypeUsageProviderTestClass = value;
                // *** Start programmer edit section *** (CombinedTypesUsageProviderTestClass.TypeUsageProviderTestClass Set end)

                // *** End programmer edit section *** (CombinedTypesUsageProviderTestClass.TypeUsageProviderTestClass Set end)
            }
        }
    }
    
    /// <summary>
    /// Detail array of CombinedTypesUsageProviderTestClass.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfCombinedTypesUsageProviderTestClass CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfCombinedTypesUsageProviderTestClass CustomAttributes)
    public class DetailArrayOfCombinedTypesUsageProviderTestClass : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (NewPlatform.ClickHouseDataService.Tests.DetailArrayOfCombinedTypesUsageProviderTestClass members)

        // *** End programmer edit section *** (NewPlatform.ClickHouseDataService.Tests.DetailArrayOfCombinedTypesUsageProviderTestClass members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type CombinedTypesUsageProviderTestClass by index.
        /// </summary>
        /// <summary>
        /// Adds object with type CombinedTypesUsageProviderTestClass.
        /// </summary>
        public DetailArrayOfCombinedTypesUsageProviderTestClass(NewPlatform.ClickHouseDataService.Tests.TypeUsageProviderTestClass fTypeUsageProviderTestClass) : 
                base(typeof(CombinedTypesUsageProviderTestClass), ((ICSSoft.STORMNET.DataObject)(fTypeUsageProviderTestClass)))
        {
        }
        
        public NewPlatform.ClickHouseDataService.Tests.CombinedTypesUsageProviderTestClass this[int index]
        {
            get
            {
                return ((NewPlatform.ClickHouseDataService.Tests.CombinedTypesUsageProviderTestClass)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(NewPlatform.ClickHouseDataService.Tests.CombinedTypesUsageProviderTestClass dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
