//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.ClickHouseDataService.Tests
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// InformationTestClass2.
    /// </summary>
    // *** Start programmer edit section *** (InformationTestClass2 CustomAttributes)

    // *** End programmer edit section *** (InformationTestClass2 CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class InformationTestClass2 : ICSSoft.STORMNET.DataObject
    {
        
        private string fStringPropertyForInformationTestClass2;
        
        private NewPlatform.ClickHouseDataService.Tests.InformationTestClass fInformationTestClass;
        
        // *** Start programmer edit section *** (InformationTestClass2 CustomMembers)

        // *** End programmer edit section *** (InformationTestClass2 CustomMembers)

        
        /// <summary>
        /// StringPropertyForInformationTestClass2.
        /// </summary>
        // *** Start programmer edit section *** (InformationTestClass2.StringPropertyForInformationTestClass2 CustomAttributes)

        // *** End programmer edit section *** (InformationTestClass2.StringPropertyForInformationTestClass2 CustomAttributes)
        [PropertyStorage("StringPropertyForInfTestClass2")]
        [StrLen(255)]
        public virtual string StringPropertyForInformationTestClass2
        {
            get
            {
                // *** Start programmer edit section *** (InformationTestClass2.StringPropertyForInformationTestClass2 Get start)

                // *** End programmer edit section *** (InformationTestClass2.StringPropertyForInformationTestClass2 Get start)
                string result = this.fStringPropertyForInformationTestClass2;
                // *** Start programmer edit section *** (InformationTestClass2.StringPropertyForInformationTestClass2 Get end)

                // *** End programmer edit section *** (InformationTestClass2.StringPropertyForInformationTestClass2 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (InformationTestClass2.StringPropertyForInformationTestClass2 Set start)

                // *** End programmer edit section *** (InformationTestClass2.StringPropertyForInformationTestClass2 Set start)
                this.fStringPropertyForInformationTestClass2 = value;
                // *** Start programmer edit section *** (InformationTestClass2.StringPropertyForInformationTestClass2 Set end)

                // *** End programmer edit section *** (InformationTestClass2.StringPropertyForInformationTestClass2 Set end)
            }
        }
        
        /// <summary>
        /// InformationTestClass2.
        /// </summary>
        // *** Start programmer edit section *** (InformationTestClass2.InformationTestClass CustomAttributes)

        // *** End programmer edit section *** (InformationTestClass2.InformationTestClass CustomAttributes)
        [PropertyStorage("InformationTestClass")]
        [TypeUsage(new string[] {
                "NewPlatform.ClickHouseDataService.Tests.InformationTestClass",
                "NewPlatform.ClickHouseDataService.Tests.InformationTestClassChild"})]
        [NotNull()]
        public virtual NewPlatform.ClickHouseDataService.Tests.InformationTestClass InformationTestClass
        {
            get
            {
                // *** Start programmer edit section *** (InformationTestClass2.InformationTestClass Get start)

                // *** End programmer edit section *** (InformationTestClass2.InformationTestClass Get start)
                NewPlatform.ClickHouseDataService.Tests.InformationTestClass result = this.fInformationTestClass;
                // *** Start programmer edit section *** (InformationTestClass2.InformationTestClass Get end)

                // *** End programmer edit section *** (InformationTestClass2.InformationTestClass Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (InformationTestClass2.InformationTestClass Set start)

                // *** End programmer edit section *** (InformationTestClass2.InformationTestClass Set start)
                this.fInformationTestClass = value;
                // *** Start programmer edit section *** (InformationTestClass2.InformationTestClass Set end)

                // *** End programmer edit section *** (InformationTestClass2.InformationTestClass Set end)
            }
        }
    }
}
