//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.ClickHouseDataService.Tests
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// MasterClass.
    /// </summary>
    // *** Start programmer edit section *** (MasterClass CustomAttributes)

    // *** End programmer edit section *** (MasterClass CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("MasterClassE", new string[] {
            "StringMasterProperty"})]
    [AssociatedDetailViewAttribute("MasterClassE", "DetailClass", "DetailClassE", true, "|DetailClass", "DetailClass", true, new string[] {
            ""})]
    [View("MasterClassL", new string[] {
            "StringMasterProperty",
            "InformationTestClass",
            "InformationTestClass.PublicStringProperty",
            "InformationTestClass2.InformationTestClass",
            "InformationTestClass2.InformationTestClass.PublicStringProperty",
            "InformationTestClass2.InformationTestClass.StringPropertyForInformationTestClass",
            "InformationTestClass3",
            "InformationTestClass3.StringPropertyForInformationTestClass3"})]
    [View("Test_MasterClassE", new string[] {
            "StringMasterProperty as \'StringMasterProperty\'",
            "IntMasterProperty"})]
    [AssociatedDetailViewAttribute("Test_MasterClassE", "DetailClass", "Test_DetailClassE", true, "", "Detail class", true, new string[] {
            ""})]
    [View("Test_MasterClassL", new string[] {
            "StringMasterProperty as \'StringMasterProperty\'"})]
    public class MasterClass : ICSSoft.STORMNET.DataObject
    {
        
        private string fStringMasterProperty;
        
        private NewPlatform.ClickHouseDataService.Tests.InformationTestClass3 fInformationTestClass3;
        
        private NewPlatform.ClickHouseDataService.Tests.InformationTestClass2 fInformationTestClass2;
        
        private NewPlatform.ClickHouseDataService.Tests.InformationTestClass fInformationTestClass;
        
        private NewPlatform.ClickHouseDataService.Tests.DetailArrayOfDetailClass fDetailClass;
        
        // *** Start programmer edit section *** (MasterClass CustomMembers)

        // *** End programmer edit section *** (MasterClass CustomMembers)

        
        /// <summary>
        /// StringMasterProperty.
        /// </summary>
        // *** Start programmer edit section *** (MasterClass.StringMasterProperty CustomAttributes)

        // *** End programmer edit section *** (MasterClass.StringMasterProperty CustomAttributes)
        [StrLen(255)]
        public virtual string StringMasterProperty
        {
            get
            {
                // *** Start programmer edit section *** (MasterClass.StringMasterProperty Get start)

                // *** End programmer edit section *** (MasterClass.StringMasterProperty Get start)
                string result = this.fStringMasterProperty;
                // *** Start programmer edit section *** (MasterClass.StringMasterProperty Get end)

                // *** End programmer edit section *** (MasterClass.StringMasterProperty Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (MasterClass.StringMasterProperty Set start)

                // *** End programmer edit section *** (MasterClass.StringMasterProperty Set start)
                this.fStringMasterProperty = value;
                // *** Start programmer edit section *** (MasterClass.StringMasterProperty Set end)

                // *** End programmer edit section *** (MasterClass.StringMasterProperty Set end)
            }
        }
        
        /// <summary>
        /// IntMasterProperty.
        /// </summary>
        // *** Start programmer edit section *** (MasterClass.IntMasterProperty CustomAttributes)

        // *** End programmer edit section *** (MasterClass.IntMasterProperty CustomAttributes)
        [ICSSoft.STORMNET.NotStored()]
        public virtual int IntMasterProperty
        {
            get
            {
                // *** Start programmer edit section *** (MasterClass.IntMasterProperty Get)

                return 0;
                // *** End programmer edit section *** (MasterClass.IntMasterProperty Get)
            }
            set
            {
                // *** Start programmer edit section *** (MasterClass.IntMasterProperty Set)

                // *** End programmer edit section *** (MasterClass.IntMasterProperty Set)
            }
        }
        
        /// <summary>
        /// MasterClass.
        /// </summary>
        // *** Start programmer edit section *** (MasterClass.InformationTestClass3 CustomAttributes)

        // *** End programmer edit section *** (MasterClass.InformationTestClass3 CustomAttributes)
        public virtual NewPlatform.ClickHouseDataService.Tests.InformationTestClass3 InformationTestClass3
        {
            get
            {
                // *** Start programmer edit section *** (MasterClass.InformationTestClass3 Get start)

                // *** End programmer edit section *** (MasterClass.InformationTestClass3 Get start)
                NewPlatform.ClickHouseDataService.Tests.InformationTestClass3 result = this.fInformationTestClass3;
                // *** Start programmer edit section *** (MasterClass.InformationTestClass3 Get end)

                // *** End programmer edit section *** (MasterClass.InformationTestClass3 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (MasterClass.InformationTestClass3 Set start)

                // *** End programmer edit section *** (MasterClass.InformationTestClass3 Set start)
                this.fInformationTestClass3 = value;
                // *** Start programmer edit section *** (MasterClass.InformationTestClass3 Set end)

                // *** End programmer edit section *** (MasterClass.InformationTestClass3 Set end)
            }
        }
        
        /// <summary>
        /// MasterClass.
        /// </summary>
        // *** Start programmer edit section *** (MasterClass.InformationTestClass2 CustomAttributes)

        // *** End programmer edit section *** (MasterClass.InformationTestClass2 CustomAttributes)
        [PropertyStorage(new string[] {
                "InformationTestClass2"})]
        public virtual NewPlatform.ClickHouseDataService.Tests.InformationTestClass2 InformationTestClass2
        {
            get
            {
                // *** Start programmer edit section *** (MasterClass.InformationTestClass2 Get start)

                // *** End programmer edit section *** (MasterClass.InformationTestClass2 Get start)
                NewPlatform.ClickHouseDataService.Tests.InformationTestClass2 result = this.fInformationTestClass2;
                // *** Start programmer edit section *** (MasterClass.InformationTestClass2 Get end)

                // *** End programmer edit section *** (MasterClass.InformationTestClass2 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (MasterClass.InformationTestClass2 Set start)

                // *** End programmer edit section *** (MasterClass.InformationTestClass2 Set start)
                this.fInformationTestClass2 = value;
                // *** Start programmer edit section *** (MasterClass.InformationTestClass2 Set end)

                // *** End programmer edit section *** (MasterClass.InformationTestClass2 Set end)
            }
        }
        
        /// <summary>
        /// MasterClass.
        /// </summary>
        // *** Start programmer edit section *** (MasterClass.InformationTestClass CustomAttributes)

        // *** End programmer edit section *** (MasterClass.InformationTestClass CustomAttributes)
        [PropertyStorage("InformationTestClass")]
        [TypeUsage(new string[] {
                "NewPlatform.ClickHouseDataService.Tests.InformationTestClass",
                "NewPlatform.ClickHouseDataService.Tests.InformationTestClassChild"})]
        public virtual NewPlatform.ClickHouseDataService.Tests.InformationTestClass InformationTestClass
        {
            get
            {
                // *** Start programmer edit section *** (MasterClass.InformationTestClass Get start)

                // *** End programmer edit section *** (MasterClass.InformationTestClass Get start)
                NewPlatform.ClickHouseDataService.Tests.InformationTestClass result = this.fInformationTestClass;
                // *** Start programmer edit section *** (MasterClass.InformationTestClass Get end)

                // *** End programmer edit section *** (MasterClass.InformationTestClass Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (MasterClass.InformationTestClass Set start)

                // *** End programmer edit section *** (MasterClass.InformationTestClass Set start)
                this.fInformationTestClass = value;
                // *** Start programmer edit section *** (MasterClass.InformationTestClass Set end)

                // *** End programmer edit section *** (MasterClass.InformationTestClass Set end)
            }
        }
        
        /// <summary>
        /// MasterClass.
        /// </summary>
        // *** Start programmer edit section *** (MasterClass.DetailClass CustomAttributes)

        // *** End programmer edit section *** (MasterClass.DetailClass CustomAttributes)
        public virtual NewPlatform.ClickHouseDataService.Tests.DetailArrayOfDetailClass DetailClass
        {
            get
            {
                // *** Start programmer edit section *** (MasterClass.DetailClass Get start)

                // *** End programmer edit section *** (MasterClass.DetailClass Get start)
                if ((this.fDetailClass == null))
                {
                    this.fDetailClass = new NewPlatform.ClickHouseDataService.Tests.DetailArrayOfDetailClass(this);
                }
                NewPlatform.ClickHouseDataService.Tests.DetailArrayOfDetailClass result = this.fDetailClass;
                // *** Start programmer edit section *** (MasterClass.DetailClass Get end)

                // *** End programmer edit section *** (MasterClass.DetailClass Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (MasterClass.DetailClass Set start)

                // *** End programmer edit section *** (MasterClass.DetailClass Set start)
                this.fDetailClass = value;
                // *** Start programmer edit section *** (MasterClass.DetailClass Set end)

                // *** End programmer edit section *** (MasterClass.DetailClass Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "MasterClassE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View MasterClassE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("MasterClassE", typeof(NewPlatform.ClickHouseDataService.Tests.MasterClass));
                }
            }
            
            /// <summary>
            /// "MasterClassL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View MasterClassL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("MasterClassL", typeof(NewPlatform.ClickHouseDataService.Tests.MasterClass));
                }
            }
            
            /// <summary>
            /// "Test_MasterClassE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View Test_MasterClassE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("Test_MasterClassE", typeof(NewPlatform.ClickHouseDataService.Tests.MasterClass));
                }
            }
            
            /// <summary>
            /// "Test_MasterClassL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View Test_MasterClassL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("Test_MasterClassL", typeof(NewPlatform.ClickHouseDataService.Tests.MasterClass));
                }
            }
        }
    }
}
