//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.ClickHouseDataService.Tests
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Клиент.
    /// </summary>
    // *** Start programmer edit section *** (Клиент CustomAttributes)

    // *** End programmer edit section *** (Клиент CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("TestNotStoredGuid", new string[] {
            "ФИО",
            "Прописка",
            "NotStoredGuid"})]
    [View("КлиентViewE", new string[] {
            "ФИО as \'ФИО\'",
            "Прописка as \'Прописка\'"})]
    [View("КлиентViewL", new string[] {
            "ФИО as \'ФИО\'",
            "Прописка as \'Прописка\'"})]
    public class Клиент : ICSSoft.STORMNET.DataObject
    {
        
        private string fФИО;
        
        private string fПрописка;
        
        // *** Start programmer edit section *** (Клиент CustomMembers)

        // *** End programmer edit section *** (Клиент CustomMembers)

        
        /// <summary>
        /// ФИО.
        /// </summary>
        // *** Start programmer edit section *** (Клиент.ФИО CustomAttributes)

        // *** End programmer edit section *** (Клиент.ФИО CustomAttributes)
        [StrLen(255)]
        public virtual string ФИО
        {
            get
            {
                // *** Start programmer edit section *** (Клиент.ФИО Get start)

                // *** End programmer edit section *** (Клиент.ФИО Get start)
                string result = this.fФИО;
                // *** Start programmer edit section *** (Клиент.ФИО Get end)

                // *** End programmer edit section *** (Клиент.ФИО Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Клиент.ФИО Set start)

                // *** End programmer edit section *** (Клиент.ФИО Set start)
                this.fФИО = value;
                // *** Start programmer edit section *** (Клиент.ФИО Set end)

                // *** End programmer edit section *** (Клиент.ФИО Set end)
            }
        }
        
        /// <summary>
        /// Прописка.
        /// </summary>
        // *** Start programmer edit section *** (Клиент.Прописка CustomAttributes)

        // *** End programmer edit section *** (Клиент.Прописка CustomAttributes)
        [StrLen(255)]
        public virtual string Прописка
        {
            get
            {
                // *** Start programmer edit section *** (Клиент.Прописка Get start)

                // *** End programmer edit section *** (Клиент.Прописка Get start)
                string result = this.fПрописка;
                // *** Start programmer edit section *** (Клиент.Прописка Get end)

                // *** End programmer edit section *** (Клиент.Прописка Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Клиент.Прописка Set start)

                // *** End programmer edit section *** (Клиент.Прописка Set start)
                this.fПрописка = value;
                // *** Start programmer edit section *** (Клиент.Прописка Set end)

                // *** End programmer edit section *** (Клиент.Прописка Set end)
            }
        }
        
        /// <summary>
        /// NotStoredGuid.
        /// </summary>
        // *** Start programmer edit section *** (Клиент.NotStoredGuid CustomAttributes)

        // *** End programmer edit section *** (Клиент.NotStoredGuid CustomAttributes)
        [ICSSoft.STORMNET.NotStored()]
        [StrLen(255)]
        [DataServiceExpression(typeof(NewPlatform.Flexberry.ORM.ClickHouseDataService), "select newid()")]
        [TrimmedStringStorage(false)]
        public virtual string NotStoredGuid
        {
            get
            {
                // *** Start programmer edit section *** (Клиент.NotStoredGuid Get)

                return null;
                // *** End programmer edit section *** (Клиент.NotStoredGuid Get)
            }
            set
            {
                // *** Start programmer edit section *** (Клиент.NotStoredGuid Set)

                // *** End programmer edit section *** (Клиент.NotStoredGuid Set)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// Проверка загрузки по представлению, где есть особый нехранимый идентификатор.
            /// </summary>
            public static ICSSoft.STORMNET.View TestNotStoredGuid
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("TestNotStoredGuid", typeof(NewPlatform.ClickHouseDataService.Tests.Клиент));
                }
            }
            
            /// <summary>
            /// "КлиентViewE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КлиентViewE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КлиентViewE", typeof(NewPlatform.ClickHouseDataService.Tests.Клиент));
                }
            }
            
            /// <summary>
            /// "КлиентViewL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КлиентViewL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КлиентViewL", typeof(NewPlatform.ClickHouseDataService.Tests.Клиент));
                }
            }
        }
    }
}
