//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.ClickHouseDataService.Tests
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Этап.
    /// </summary>
    // *** Start programmer edit section *** (Этап CustomAttributes)

    // *** End programmer edit section *** (Этап CustomAttributes)
    [AutoAltered()]
    [ICSSoft.STORMNET.NotStored()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class Этап : ICSSoft.STORMNET.DataObject
    {
        
        private NewPlatform.ClickHouseDataService.Tests.СтатусЗапроса fСтатус;
        
        private NewPlatform.ClickHouseDataService.Tests.КонфигурацияЭтапа fКонфигурацияЭтапа;
        
        private NewPlatform.ClickHouseDataService.Tests.Запрос fЗапрос;
        
        // *** Start programmer edit section *** (Этап CustomMembers)

        // *** End programmer edit section *** (Этап CustomMembers)

        
        /// <summary>
        /// Статус.
        /// </summary>
        // *** Start programmer edit section *** (Этап.Статус CustomAttributes)

        // *** End programmer edit section *** (Этап.Статус CustomAttributes)
        public virtual NewPlatform.ClickHouseDataService.Tests.СтатусЗапроса Статус
        {
            get
            {
                // *** Start programmer edit section *** (Этап.Статус Get start)

                // *** End programmer edit section *** (Этап.Статус Get start)
                NewPlatform.ClickHouseDataService.Tests.СтатусЗапроса result = this.fСтатус;
                // *** Start programmer edit section *** (Этап.Статус Get end)

                // *** End programmer edit section *** (Этап.Статус Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Этап.Статус Set start)

                // *** End programmer edit section *** (Этап.Статус Set start)
                this.fСтатус = value;
                // *** Start programmer edit section *** (Этап.Статус Set end)

                // *** End programmer edit section *** (Этап.Статус Set end)
            }
        }
        
        /// <summary>
        /// Этап.
        /// </summary>
        // *** Start programmer edit section *** (Этап.КонфигурацияЭтапа CustomAttributes)

        // *** End programmer edit section *** (Этап.КонфигурацияЭтапа CustomAttributes)
        [NotNull()]
        public virtual NewPlatform.ClickHouseDataService.Tests.КонфигурацияЭтапа КонфигурацияЭтапа
        {
            get
            {
                // *** Start programmer edit section *** (Этап.КонфигурацияЭтапа Get start)

                // *** End programmer edit section *** (Этап.КонфигурацияЭтапа Get start)
                NewPlatform.ClickHouseDataService.Tests.КонфигурацияЭтапа result = this.fКонфигурацияЭтапа;
                // *** Start programmer edit section *** (Этап.КонфигурацияЭтапа Get end)

                // *** End programmer edit section *** (Этап.КонфигурацияЭтапа Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Этап.КонфигурацияЭтапа Set start)

                // *** End programmer edit section *** (Этап.КонфигурацияЭтапа Set start)
                this.fКонфигурацияЭтапа = value;
                // *** Start programmer edit section *** (Этап.КонфигурацияЭтапа Set end)

                // *** End programmer edit section *** (Этап.КонфигурацияЭтапа Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку NewPlatform.ClickHouseDataService.Tests.Запрос.
        /// </summary>
        // *** Start programmer edit section *** (Этап.Запрос CustomAttributes)

        // *** End programmer edit section *** (Этап.Запрос CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Запрос"})]
        public virtual NewPlatform.ClickHouseDataService.Tests.Запрос Запрос
        {
            get
            {
                // *** Start programmer edit section *** (Этап.Запрос Get start)

                // *** End programmer edit section *** (Этап.Запрос Get start)
                NewPlatform.ClickHouseDataService.Tests.Запрос result = this.fЗапрос;
                // *** Start programmer edit section *** (Этап.Запрос Get end)

                // *** End programmer edit section *** (Этап.Запрос Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Этап.Запрос Set start)

                // *** End programmer edit section *** (Этап.Запрос Set start)
                this.fЗапрос = value;
                // *** Start programmer edit section *** (Этап.Запрос Set end)

                // *** End programmer edit section *** (Этап.Запрос Set end)
            }
        }
    }
    
    /// <summary>
    /// Detail array of Этап.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfЭтап CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfЭтап CustomAttributes)
    public class DetailArrayOfЭтап : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (NewPlatform.ClickHouseDataService.Tests.DetailArrayOfЭтап members)

        // *** End programmer edit section *** (NewPlatform.ClickHouseDataService.Tests.DetailArrayOfЭтап members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type Этап by index.
        /// </summary>
        /// <summary>
        /// Adds object with type Этап.
        /// </summary>
        public DetailArrayOfЭтап(NewPlatform.ClickHouseDataService.Tests.Запрос fЗапрос) : 
                base(typeof(Этап), ((ICSSoft.STORMNET.DataObject)(fЗапрос)))
        {
        }
        
        public NewPlatform.ClickHouseDataService.Tests.Этап this[int index]
        {
            get
            {
                return ((NewPlatform.ClickHouseDataService.Tests.Этап)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(NewPlatform.ClickHouseDataService.Tests.Этап dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
